/**
CREATE TABLE DEPT (
	DEPTNO NUMBER(4) PRIMARY KEY,
	DNAME VARCHAR(24) NOT NULL,
	LOC VARCHAR2(24) NOT NULL
	);


INSERT INTO DEPT VALUES(10, 'ACCOUNTING','ULSAN');
INSERT INTO DEPT VALUES(20, 'RESEARCH','SEOUL');
INSERT INTO DEPT VALUES(30, 'SALE','BUNDANG');
INSERT INTO DEPT VALUES(40, 'NONE','NEWYORK');
*/
SELECT * FROM DEPT;